### PR TITLE
Button Alerts

### PR DESCRIPTION
**Pull request by nkehle**
Added some very simple window popup alerts for when you press certain buttons. Will work on styling them to match out theme this weekend with the alertBox function.

### CODE REVIEW

**Review by isaacschiffler — APPROVED** [review]
Everything looks good to me

**Comment by Apoak** [comment]
I approve.

**Comment by mushu-bytes** [comment]
looks good to me. Clean and simple!

**Comment by tylerpbrady** [comment]
Looks good! Thanks Noa

**Pull request merged**
