### PR TITLE
Issue13 - Game Detail Page + little more

### PR DESCRIPTION
**Pull request by isaacschiffler**
Mostly made edits with creating the individual game detail page. Also had to make some minor changes in MyApp and GamePreview. Also minor edit to Header to make it all in-line.

### CODE REVIEW

**Comment by mushu-bytes** [comment]
looks good to me. Verify that the merge conflicts have been merged, and I think its ready to be pulled! I like what you did with the design of each game card

**Comment by nkehle** [comment]
Looks great! You can model the react fragment like this:

`<Route path="/create-game"
              element={
                <React.Fragment>
                  <Header />
                  <CreateGame path="/create-game" updateList={updateList} />
                </React.Fragment>
              }
          />`

**Comment by isaacschiffler** [comment]
> Looks great! You can model the react fragment like this:
> 
> `<Route path="/create-game" element={ <React.Fragment> <Header /> <CreateGame path="/create-game" updateList={updateList} /> </React.Fragment> } />`

Sounds good. Will add this to remove conflicts with main

**Comment by Apoak** [comment]
> > Looks great! You can model the react fragment like this:
> > `<Route path="/create-game" element={ <React.Fragment> <Header /> <CreateGame path="/create-game" updateList={updateList} /> </React.Fragment> } />`
> 
> Sounds good. Will add this to remove conflicts with main

In agreement, looks good.

**Pull request merged**
