### PR TITLE
Moving authentication from storing credentials in state to storing credentials in the databse

### PR DESCRIPTION
**Pull request by mushu-bytes**
changes are mainly in auth. When a user signs up, a user is created in the database. When the user logins in, the hashed password is retrieved from the database.

### CODE REVIEW

**Review by isaacschiffler — APPROVED** [review]
All looks good to me. Good to merge if it works

**Comment by nkehle** [comment]
Looks good to me. Approve.

**Comment by Apoak** [comment]
I approve, looks good.

**Comment by tylerpbrady** [comment]
Looks good to me, thanks Damon

**Pull request merged**
